sonar.projectKey=CervoSoft_cervo-mutant
sonar.projectName=CervoMutant
sonar.projectVersion=0.1

sonar.sources=cmd,pkg
sonar.tests=cmd,pkg
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/vendor/**,**/.cervomut/**,**/testdata/**,**/fixtures/**,**/*.html,**/*.xml,**/*.json

sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out

sonar.links.scm=https://github.com/cervantesh/cervo-mutants
sonar.links.issue=https://github.com/cervantesh/cervo-mutants/issues
