sonar.projectKey=cervantesh_CervoMutants
sonar.projectName=CervoMutants
sonar.projectVersion=0.1

sonar.sources=cmd,pkg
sonar.tests=cmd,pkg
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/vendor/**,**/.cervomut/**,**/testdata/**,**/fixtures/**,**/*.html,**/*.xml,**/*.json

sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out

sonar.links.scm=https://github.com/cervantesh/CervoMutants
sonar.links.issue=https://github.com/cervantesh/CervoMutants/issues

